"""User model

Revision ID: 2598098898ff
Revises: 
Create Date: 2025-11-12 12:33:28.474024

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.config import settings
from src.database.models.user import UserRole

# revision identifiers, used by Alembic.
revision: str = '2598098898ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.BigInteger(), primary_key=True),
                    sa.Column('email', sa.String(length=255)),
                    sa.Column('sub', sa.String(length=255), nullable=False, unique=True),
                    sa.Column('role', sa.Enum('admin', 'user', name='role', create_constraint=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text("timezone('utc', now())"), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text("timezone('utc', now())"), nullable=False),

                    sa.Column("telegram_chat_id", sa.BigInteger(), nullable=True),
                    sa.Column("telegram_username", sa.String(length=255), nullable=True),
                    sa.Column("telegram_verified_at", sa.DateTime(timezone=True), nullable=True),

                    sa.UniqueConstraint('email', name='uq_users_email'),
                    sa.UniqueConstraint('sub', name='uq_users_sub'),
                    )
    op.create_index(
        'ix_users_role',
        'users',
        ['role']
    )

    op.create_index(
        'ix_users_created_at',
        'users',
        ['created_at']
    )
    op.create_index("ix_users_telegram_chat_id", "users", ["telegram_chat_id"], unique=False)
    # ### end Alembic commands ###
    admin_email = settings.admin_data.ADMIN_EMAIL
    admin_sub = settings.admin_data.ADMIN_SUB
    admin_role = UserRole.admin.value
    now = datetime.now(timezone.utc)

    op.execute(
        f"""
        INSERT INTO "users" (email, sub, role, created_at, updated_at)
        VALUES (
            '{admin_email}',
            '{admin_sub}',
            '{admin_role}',
            '{now}',
            '{now}'
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index("ix_users_telegram_chat_id", table_name="users")
    op.drop_table('users')
    op.execute("DROP TYPE role;")
    # ### end Alembic commands ###
