"""Profile table

Revision ID: c16b4f027942
Revises: 2598098898ff
Create Date: 2025-11-14 11:05:10.932513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c16b4f027942'
down_revision: Union[str, Sequence[str], None] = '2598098898ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
                    sa.Column('id', sa.BigInteger(), primary_key=True),
                    sa.Column('user_id', sa.BigInteger(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False,
                              unique=True),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('avatar_path', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),server_default=sa.text("timezone('utc', now())"), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),server_default=sa.text("timezone('utc', now())"), nullable=False),

                    )
    op.create_index(
        'ix_profiles_username',
        'profiles',
        ['username']
    )

    op.create_index(
        'ix_profiles_age',
        'profiles',
        ['age']
    )

    op.create_index(
        'ix_profiles_created_at',
        'profiles',
        ['created_at']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profiles_created_at', table_name='profiles')
    op.drop_index('ix_profiles_age', table_name='profiles')
    op.drop_index('ix_profiles_username', table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
