"""User model

Revision ID: 2598098898ff
Revises: 
Create Date: 2025-11-12 12:33:28.474024

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.config import settings
from src.database.models.user import UserRole

# revision identifiers, used by Alembic.
revision: str = '2598098898ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('email', sa.String(length=50), nullable=False),
                    sa.Column('sub', sa.String(length=255), nullable=False, unique=True),
                    sa.Column('role', sa.Enum('admin', 'user', name='role', create_constraint=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###
    admin_email = settings.admin_data.ADMIN_EMAIL
    admin_sub = settings.admin_data.ADMIN_SUB
    admin_role = UserRole.admin.value
    now = datetime.utcnow()

    op.execute(
        f"""
        INSERT INTO "users" (email, sub, role, created_at, updated_at)
        VALUES (
            '{admin_email}',
            '{admin_sub}',
            '{admin_role}',
            '{now}',
            '{now}'
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.execute("DROP TYPE role;")
    # ### end Alembic commands ###
