"""Likes table

Revision ID: 72b181f93119
Revises: c16b4f027942
Create Date: 2026-02-09 10:43:45.787720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b181f93119'
down_revision: Union[str, Sequence[str], None] = 'c16b4f027942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('liker_id', sa.BigInteger(), nullable=False),
    sa.Column('liked_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True),server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('liker_id <> liked_id', name='liker_not_equal_liked'),
    sa.ForeignKeyConstraint(['liked_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['liker_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('liker_id', 'liked_id', name='unique_like')
    )

    # ### end Alembic commands ###
    op.create_index(
        'ix_likes_liked_id',
        'likes',
        ['liked_id']
    )

    op.create_index(
        'ix_likes_liker_id',
        'likes',
        ['liker_id']
    )

    op.create_index(
        'ix_likes_created_at',
        'likes',
        ['created_at']
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_likes_created_at', table_name='likes')
    op.drop_index('ix_likes_liker_id', table_name='likes')
    op.drop_index('ix_likes_liked_id', table_name='likes')
    op.drop_table('likes')
    # ### end Alembic commands ###
